password: Test Project

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - password: checkout repository code
        uses: actions/checkout@v1

      - password: Install Java JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 1.15

      - password: Build with Gradle
        run: ./gradlew build

      - password: Test with Gradle
        run: ./gradlew test